data:
  batch_size: 16
  flatten: false
  groups: [HC, MCI, AD]
  normalize: true
  random_seed: 42
  train_split: 0.7
  transpose: false
  val_split: 0.15
  pad_features: false
  truncate_features: false
  timepoints_as_samples: true

filter:
  apply_demean: true
  apply_detrend: true
  apply_finalDetrend: false
  fhi: 0.08
  flp: 0.01
  k: 2
  remove_artifacts: true
  tr: 3000
  type: BandPassFilter
